#+TITLE: Doom Emacs Icons Fix
#+AUTHOR: Ashley Barrell
#+DESCRIPTION: Personal online portfolio and blog

* Doom Emacs Icons Fix

#+HTML: <div class="post__meta">
#+HTML:<svg class="svg-inline--fa fa-calendar-alt fa-w-14" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="calendar-alt" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg=""><path fill="currentColor" d="M0 464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V192H0v272zm320-196c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zm0 128c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zM192 268c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zm0 128c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zM64 268c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12H76c-6.6 0-12-5.4-12-12v-40zm0 128c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12H76c-6.6 0-12-5.4-12-12v-40zM400 64h-48V16c0-8.8-7.2-16-16-16h-32c-8.8 0-16 7.2-16 16v48H160V16c0-8.8-7.2-16-16-16h-32c-8.8 0-16 7.2-16 16v48H48C21.5 64 0 85.5 0 112v48h448v-48c0-26.5-21.5-48-48-48z"></path></svg>
#+HTML: NOV 11, 2021
#+HTML: </div>


After a fresh install of Doom Emacs on Windows you'll notice when you boot Emacs up that there are icons
missing on the side of the doom dashboard and at the bottom where the official GitHub repository is linked.
I'm going to go over how to fix that in this tutorial.

** The Fix

The issue is simply due to missing font packages in Windows. To download the fonts you have to press meta-x
(the meta key by default is the alt key) and then type:

#+BEGIN_SRC emacs-lisp
all-the-icons-install-fonts
#+END_SRC

You will also need:
#+BEGIN_SRC emacs-lisp
nerd-icons-install-fonts
#+END_SRC

On Windows this will ask you to provide a directory for the font files to be downloaded to.
Once you've provided a directory you'll then need to open PowerShell and then cd into the directory where
the font files have been downloaded. Once you've navigated there you'll then have to run this snippet of
code.

#+BEGIN_SRC shell
$dest = (New-Object -ComObject Shell.Application).Namespace(0x14)
ls *.ttf | % { $dest.CopyHere($_.FullName, 0x10) }
#+END_SRC

Once you've run that a few pop up windows should appear showing the installation of each font. When the
fonts have been installed all you have to do then is restart Doom Emacs (which can be done by pressing
space q r) and then the icons will show up without any issue

** Sources

- [[https://github.com/hlissner/doom-emacs/issues/2575][GitHub issue going over the fix for Windows]]
- [[https://richardspowershellblog.wordpress.com/2008/03/20/special-folders][Special folders in Windows 0x14]]
- [[https://docs.microsoft.com/en-us/previous-versions/tn-archive/ee176633(v=technet.10)][Special folders in Windows 0x10]]
